### ISSUE TITLE
Array of Arrays

### ISSUE THREAD

**Issue by DaveyJake** [jsonquerylang/jsonquery#4]
Can you provide an example of how to use `jsonquery` to filter a multidimensional array aka an array of arrays?

For example, how would I go about filtering these bid elements in order to group them by matching properties and adding a new `count` property?
```json
{
  "bids": [
    [
      "67141.39",
      "0.04299999",
      "36e1216e-93ed-48e2-acc7-d9e348b1c880"
    ],
    [
      "67141.39",
      "0.00022876",
      "d459b1d0-4eea-46e2-99a0-f87b4d136b3d"
    ],
    [
      "67140.56",
      "0.04299999",
      "83ef5611-e636-4d73-9fda-1d0988222119"
    ],
    [
      "67139.72",
      "0.08244684",
      "3a735d20-9303-49cc-a729-83ead06563dc"
    ],
    [
      "0.1",
      "10",
      "55c9ec6d-dd01-47e3-9086-550f345f5017"
    ],
    [
      "0.1",
      "1",
      "4b5641e7-d543-4d07-b76c-1a2a880876a2"
    ],
    [
      "0.1",
      "200",
      "b5da2b53-68fb-40d0-b3e9-5a7a08b25848"
    ],
    [
      "0.1",
      "32.5038",
      "53b8d0c1-eaf4-4780-97af-2e4764fbefa6"
    ],
    [
      "0.1",
      "10",
      "5eeffc24-3cd1-4eca-bdf3-177f02171586"
    ],
    [
      "0.1",
      "10",
      "635d658d-b591-4283-b774-f692e1354f2f"
    ]
  ]
}
```

**Comment by macintacos** [comment]
@DaveyJake I think the key is understanding that `map()` can iterate over arrays, and you can do whatever you want with those arrays (including use functions within the map, and build objects with the results you want).

For example with your input, I used the following to try summing up the first two value in each bid, use the third value as the "id", and create a "count" value:

```
.bids | map({id: .2, sum: .0 + .1, count: size()})
```

Here's what that looks like on https://jsonquerylang.org

![CleanShot 2024-11-06 at 22 49 56@2x](https://github.com/user-attachments/assets/2558abfb-b388-4fc1-9e62-35f849167e50)

...as you can see, it combines things the way you'd expect. However, it doesn't appear that you can directly coerce a string into a number for example, so the "math" that's supposed to be happening isn't really happening.

Anyway, hope that helps.

**Comment by josdejong** [comment]
Well explained Julian, thanks.

I'll close this question now @DaveyJake, please reopen if needed.
