### ISSUE TITLE
Correct reference doc about result of pick function 

### ISSUE THREAD

**Issue by lateapexearlyspeed** [jsonquerylang/jsonquery#7]
Hi,

Current [doc](https://github.com/jsonquerylang/jsonquery/blob/6ef708f1650fceaa453f14b171de49b246c6196a/reference/functions.md?plain=1#L269) should be corrected:

```
const item = { "price": 25 }
jsonquery(item, 'pick(.price)') // 25
```

the actual result should be `{ "price": 25 }` which has been verified by https://jsonquerylang.org/.

**Comment by josdejong** [comment]
Thanks for reporting, fixed now via 781e7ddfe6fe42a5f3d09efc4946ac2713f53a33.
